//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AES
    {
        public int idAes { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string token { get; set; }
        public string iv { get; set; }
        public int estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
