//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int id { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string correo2 { get; set; }
        public string twitter { get; set; }
        public string insta { get; set; }
        public string facebook { get; set; }
    }
}
