//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonacionEspecies
    {
        public int id { get; set; }
        public string tipoEspecie { get; set; }
        public double cantidad { get; set; }
        public string unidadMedida { get; set; }
        public System.DateTime fecha { get; set; }
        public int donanteId { get; set; }
        public int estado { get; set; }
    
        public virtual Donante Donante { get; set; }
    }
}
