//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidente
    {
        public int id { get; set; }
        public Nullable<int> nivelRiesgoId { get; set; }
        public string descripcion { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> residenteId { get; set; }
        public int usuarioId { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int estado { get; set; }
    
        public virtual NivelDeRiesgo NivelDeRiesgo { get; set; }
        public virtual Residente Residente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
