//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoBancaria
    {
        public int id { get; set; }
        public string banco { get; set; }
        public string numeroCuenta { get; set; }
        public string moneda { get; set; }
        public int estado { get; set; }
    }
}
