//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mininosDatabaseEntities : DbContext
    {
        public mininosDatabaseEntities()
            : base("name=mininosDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AES> AES { get; set; }
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<DonacionEspecies> DonacionEspecies { get; set; }
        public virtual DbSet<DonacionMonetaria> DonacionMonetaria { get; set; }
        public virtual DbSet<Donante> Donante { get; set; }
        public virtual DbSet<Incidente> Incidente { get; set; }
        public virtual DbSet<InfoBancaria> InfoBancaria { get; set; }
        public virtual DbSet<NivelDeRiesgo> NivelDeRiesgo { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<Patologia> Patologia { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<Residente> Residente { get; set; }
        public virtual DbSet<ResidenteDonante> ResidenteDonante { get; set; }
        public virtual DbSet<ResidentePatologia> ResidentePatologia { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolOpcion> RolOpcion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
    }
}
