//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public int id { get; set; }
        public byte[] fotoPublicacion { get; set; }
        public string titulo { get; set; }
        public string tipo { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha { get; set; }
        public int estado { get; set; }
    }
}
